import matplotlib.pyplot as plt
import numpy as np
r = np.loadtxt('r.txt')
corr_gg = np.loadtxt('corr_gg.txt')
corr_gg_0 = np.loadtxt('corr_gg_0.txt')
corr_gg_2 = np.loadtxt('corr_gg_2.txt')
corr_gg_4 = np.loadtxt('corr_gg_4.txt')
fig, ax = plt.subplots(figsize=(16,9), tight_layout=True)
ax.grid(True)
ax.plot(r, corr_gg, lw=2, label='corr_gg')
ax.plot(r, corr_gg_0, lw=2, label='corr_gg_0')
ax.plot(r, corr_gg_2, lw=2, label='corr_gg_2')
ax.plot(r, corr_gg_4, lw=2, label='corr_gg_4')
ax.set_xlabel(r'$r$', fontsize=18)
ax.set_ylabel(r'Correlation', fontsize=18)
ax.set_xscale('log')
ax.set_yscale('log')
ax.set_xlim(1, 100)
ax.legend(loc='best', fontsize=16)
plt.savefig('corr_gg_plot.png', dpi=300)
plt.close()